name: u24_element_mkdocs-build
on:
  push:
    branches:
      - '**' # every branch
      - '!gh-pages' # exclude gh-pages branch
      - '!stage*' # exclude branches beginning with stage
    tags:
      - '\d+\.\d+\.\d+' # only semver tags
  pull_request:
    branches:
      - '**' # every branch
      - '!gh-pages' # exclude gh-pages branch
      - '!stage*' # exclude branches beginning with stage
jobs:
  publish-docs:
    if: |
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        run: |
          ELEMENT_HYPHENS=${GITHUB_REPOSITORY##*/}
          ELEMENT_UNDERSCORES=${ELEMENT_HYPHENS//-/_}
          export MODE=BUILD
          export PACKAGE=${ELEMENT_UNDERSCORES}
          export UPSTREAM_REPO=https://github.com/${GITHUB_REPOSITORY}.git
          export HOST_UID=$(id -u)
          docker compose -f docs/docker-compose.yaml up --exit-code-from docs --build
          git push origin gh-pages